//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopolkoSeminar
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Zaposlenik
    {
        public int IdZaposlenik { get; set; }
        public string LoginID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        [Display (Name ="Kontakt broj")]
        public string KontaktBroj { get; set; }
        public string Ulica { get; set; }
        public string Mjesto { get; set; }
        [Display(Name = "Kucni broj")]
        public string KucniBroj { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
